name: CI
permissions:
  contents: read
on:
  push:
    branches: ["*"]
jobs:
  Test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}-test
      cancel-in-progress: true
    timeout-minutes: 2
    steps:
      - run: git clone --branch "${{ github.ref_name }}" "https://github.com/${{ github.repository }}.git" .
      - run: echo "::notice title=Go Version::$(go version)"
      - run: make test
  Lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}-lint
      cancel-in-progress: true
    timeout-minutes: 2
    steps:
      - run: git clone --branch "${{ github.ref_name }}" "https://github.com/${{ github.repository }}.git" .
      - run: make lint
